//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.OS.UserManagement.Templates.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.OS.UserManagement.Templates.Localization.EmailTexts", typeof(EmailTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordLink {
            get {
                return ResourceManager.GetString("ResetPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password using the following link:.
        /// </summary>
        internal static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ViciOne Team.
        /// </summary>
        internal static string SignOffTeam {
            get {
                return ResourceManager.GetString("SignOffTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks,.
        /// </summary>
        internal static string SignOffThanks {
            get {
                return ResourceManager.GetString("SignOffThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support.
        /// </summary>
        internal static string SupportLinkText {
            get {
                return ResourceManager.GetString("SupportLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.ifm.com/de/en/shared/service/technischer-support/technical-support.
        /// </summary>
        internal static string SupportUrl {
            get {
                return ResourceManager.GetString("SupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm my email address.
        /// </summary>
        internal static string VerifyAddressButton {
            get {
                return ResourceManager.GetString("VerifyAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not register for an account with ViciOne, please disregard this email..
        /// </summary>
        internal static string VerifyAddressDisregard {
            get {
                return ResourceManager.GetString("VerifyAddressDisregard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string VerifyAddressGreeting {
            get {
                return ResourceManager.GetString("VerifyAddressGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your account setup and access all features, please confirm your email address by clicking the button below:.
        /// </summary>
        internal static string VerifyAddressInstruction {
            get {
                return ResourceManager.GetString("VerifyAddressInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the button above does not work, please copy and paste the following link into your web browser:.
        /// </summary>
        internal static string VerifyAddressLinkFallback {
            get {
                return ResourceManager.GetString("VerifyAddressLinkFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation link:.
        /// </summary>
        internal static string VerifyAddressLinkLabel {
            get {
                return ResourceManager.GetString("VerifyAddressLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email address.
        /// </summary>
        internal static string VerifyAddressSubject {
            get {
                return ResourceManager.GetString("VerifyAddressSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with ViciOne!.
        /// </summary>
        internal static string VerifyAddressThanks {
            get {
                return ResourceManager.GetString("VerifyAddressThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email address.
        /// </summary>
        internal static string VerifyAddressTitle {
            get {
                return ResourceManager.GetString("VerifyAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming your email helps us secure your account and ensures you receive important notifications from us. Until confirmed, you may be unable to log in..
        /// </summary>
        internal static string VerifyAddressWhyText {
            get {
                return ResourceManager.GetString("VerifyAddressWhyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why confirm?.
        /// </summary>
        internal static string VerifyAddressWhyTitle {
            get {
                return ResourceManager.GetString("VerifyAddressWhyTitle", resourceCulture);
            }
        }
    }
}
