using System.Reflection;
using Core.Module;
using Core.OS.Modules.Services;
using Core.UiHosting;
using AwesomeAssertions;
using Sdk.Client.Modules;
using Sdk.Extensions;
using Sdk.Modules;
using TestModule.Backend;
using TestModule.Client;
using Xunit;

namespace Core.OS.Tests.Modules.Services;

public class UiHostEnvironmentTests
{
    public sealed class GetWwwRootFolder : UiHostEnvironmentTests
    {
        [Fact]
        public void Should_return_uihost_path_combined_with_wwwroot()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableBackendModules: false, enableUiModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext);

            // Act
            var path = hostManagement.GetWwwRootFolder();

            // Assert
            path.Should().EndWith(Constants.WwwRoot);
        }

        [Fact]
        public void Should_return_uihost_path_on_development()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableBackendModules: false, enableUiModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext)
            {
                IsDevelopment = true
            };

            // Act
            var path = hostManagement.GetWwwRootFolder();

            // Assert
            path.Should().Be(Path.GetDirectoryName(typeof(TestBackendModule).Assembly.Location));
        }
    }

    public sealed class GetModuleInfos : UiHostEnvironmentTests
    {
        private const string SkipMessage = "the moduleId is generated by the AssemblyName - the only coupling between ModuleId <-> Assembly is our naming convention. Need to find a better way!";

        [Fact(Skip = SkipMessage)]
        public void Should_return_client_module_infos()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableBackendModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext);

            // Act
            var infos = hostManagement.GetModuleMetadata();

            // Assert
            infos.Should().ContainSingle(k => k.Name == ModuleIdResolver.ResolveId<TestClientModule>());
        }

        [Fact(Skip = SkipMessage)]
        public void Should_return_backend_module_infos()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableUiHost: false, enableUiModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext);

            // Act
            var infos = hostManagement.GetModuleMetadata();

            // Assert
            infos.Should().ContainSingle(k => k.Name == ModuleIdResolver.ResolveId<TestBackendModule>());
        }
    }

    public sealed class LoadModuleBundles : UiHostEnvironmentTests
    {
        [Fact]
        [Trait(Traits.Category, Traits.System)]
        public void Should_return_bundle_for_active_ui_module()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableBackendModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext);

            // Act
            var bundles = hostManagement.LoadModuleBundles(CreateBundle).ToList();

            // Assert
            bundles.Should().HaveCount(1, "Bundle for TestModule.Client assembly");
            bundles.First().Module.ModuleKey.Should().Be(new TestBlazorServerClientModule().ModuleKey);
        }

        [Fact]
        public void Should_not_return_bundle_backend_module()
        {
            // Arrange
            var suiteContext = TestFactory.CreateSuiteContext(enableUiHost: false, enableUiModules: false);
            var hostManagement = new UiHostEnvironment(suiteContext);

            // Act
            var bundles = hostManagement.LoadModuleBundles(CreateBundle);

            // Assert
            bundles.Should().BeEmpty();
        }

        private IUiModuleBundle CreateBundle(string assemblyPath, Assembly assembly)
        {
            var modules = assembly.GetInstances<ClientModule>().First();

            return new TestUiBundle(modules, assemblyPath, assembly);
        }

        private class TestUiBundle(IModule module, string assemblyLocation, Assembly? assembly) : IUiModuleBundle
        {
            public IModule Module { get; } = module;
            public string AssemblyLocation { get; } = assemblyLocation;
            public Assembly? Assembly { get; } = assembly;
        }
    }
}
