//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Profile.ControlPanels.Passkeys.Components.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasskeysControlPanel {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasskeysControlPanel() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Profile.ControlPanels.Passkeys.Components.Localization.PasskeysControlPanel", typeof(PasskeysControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passkey sign-in is currently not available..
        /// </summary>
        internal static string FeatureNotAvailable {
            get {
                return ResourceManager.GetString("FeatureNotAvailable", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Passkeys.
        /// </summary>
        internal static string PasskeyTermPlural {
            get {
                return ResourceManager.GetString("PasskeyTermPlural", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Add or remove passkeys here to simplify how you access your account using biometrics or screen locks. Passkeys provide a safer alternative to passwords by protecting you against phishing and data breaches. Use this list to manage the specific devices you've authorized for instant entry. Please note that removing a passkey from ViciOne only revokes its access and will not delete the credential from your personal authenticator or password manager..
        /// </summary>
        internal static string PasskeysDescription {
            get {
                return ResourceManager.GetString("PasskeysDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Passkeys require access via a DNS hostname and are not available over an IP address..
        /// </summary>
        internal static string RequiresDnsHost {
            get {
                return ResourceManager.GetString("RequiresDnsHost", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Passkey settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
    }
}
