<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Properties for all projects in the repo -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <!-- general information -->
        <Description>-</Description>
        <Product>ViciOne Suite</Product>
        <Company>ifm software</Company>
        <Year>$([System.DateTime]::Now.Year)</Year>
        <Copyright>Copyright © $(Company) $(Year)</Copyright>
        <NeutralLanguage>en-US</NeutralLanguage>
        <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>
        <RunSettingsFilePath>$(MSBuildThisFileDirectory)tests.runsettings</RunSettingsFilePath>
        <!-- code quality -->
        <WarningsNotAsErrors>612,618</WarningsNotAsErrors>
        <NoWarn Condition="'$(CI)' == ''">$(NoWarn);NU1507</NoWarn>
        <!-- NuGet security -->
        <NuGetAuditMode>all</NuGetAuditMode>
    </PropertyGroup>

    <!-- For repos that contain projects published as NuGet packages -->
    <PropertyGroup>
        <!-- https://docs.microsoft.com/de-de/nuget/reference/msbuild-targets -->
        <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/suite/suite</PackageProjectUrl>
        <Authors>$(Company)</Authors>
    </PropertyGroup>

    <!-- Performance optimization for CI pipelines -->
    <PropertyGroup Condition="'$(CI)' != ''">
        <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzers>true</RunAnalyzers>
    </PropertyGroup>
    
    <!-- Do not pack or publish test projects -->
    <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
        <CompressionEnabled>false</CompressionEnabled>
    </PropertyGroup>

    <ItemGroup Condition="$(MSBuildProjectDirectory.Contains('tests'))">
        <Content Include="$(MSBuildThisFileDirectory)xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <!-- Add Test.SDK/XUnit package references to test projects -->
    <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="JunitXml.TestLogger" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ViciOne.Suite.Sdk.Testing" />
    </ItemGroup>

    <!-- Do not publish tools projects -->
    <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('tools'))">
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>
    
    <!-- For all client projects -->
    <PropertyGroup Condition="$(ProjectName.EndsWith('.Client'))">
        <!-- https://github.com/koenvzeijl/AspNetCore.SassCompiler/issues/160 -->
        <SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>
    </PropertyGroup>

    <!-- Remove SDK assemblies from backend module output folders -->
    <Target Name="EnsureSdkGetsRemovedIssue" AfterTargets="GenerateDepsFile" Condition="'$(Configuration)' == 'Release' And $(ProjectName.EndsWith('.Backend'))">
        <ItemGroup>
            <FilesToClean Include="$(TargetDir)ViciOne.Suite.Sdk.*" />
        </ItemGroup>
        <Delete Files="@(FilesToClean)"></Delete>
    </Target>
</Project>
