<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Versionierung -->
    <PropertyGroup>
        <VersionWithSuffix>$([System.IO.File]::ReadAllText('$(MsBuildThisFileDirectory)VERSION').Trim())</VersionWithSuffix>
        <!-- Version 0.1.0 ist der Standard, wenn gar keine Version gefunden wird -->
        <VersionPrefix Condition="$(VersionWithSuffix) == ''">0.1.0</VersionPrefix>
        <VersionPrefix Condition="$(VersionWithSuffix.Contains('-')) == true">$(VersionWithSuffix.Substring(0, $(VersionWithSuffix.IndexOf('-'))))</VersionPrefix>
        <VersionPrefix Condition="$(VersionWithSuffix.Contains('-')) == false">$(VersionWithSuffix)</VersionPrefix>
        <!-- Im Standardfall gibt es keinen Suffix, wenn doch wird dieser angegeben -->
        <VersionSuffix></VersionSuffix>
        <VersionSuffix Condition="$(VersionWithSuffix.Contains('-')) == true">$(VersionWithSuffix.Substring($(VersionWithSuffix.IndexOf('-'))))</VersionSuffix>
        <VersionSuffix Condition="$(VersionSuffix.Contains('-')) == true">$(VersionSuffix.Substring(1))</VersionSuffix>
        <!-- Im Standardfall ist die PackageVersion gleich der normalen "Version" -->
        <PackageVersion>$(VersionPrefix)</PackageVersion>
        <PackageVersion Condition="$(VersionSuffix) != ''">$(PackageVersion)-$(VersionSuffix)</PackageVersion>
        <!-- Wenn ein PackageVersionSuffix gegeben ist, wird dieser statt des normalen VersionPrefix verwendet -->
        <PackageVersion Condition="$(PackageVersionSuffix) != ''">$(VersionPrefix).$(PackageVersionSuffix)</PackageVersion>
    </PropertyGroup>

    <!-- Properties for all projects in the repo -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <RuntimeIdentifiers Condition="$(MSBuildProjectDirectory.Contains('src'))">linux-x64;linux-arm64;win-x64</RuntimeIdentifiers>

        <!-- General information -->
        <Description>-</Description>
        <Product>ViciOne Suite</Product>
        <Company>ifm software</Company>
        <Year>$([System.DateTime]::Now.Year)</Year>
        <Copyright>Copyright © $(Company) $(Year)</Copyright>
        <NeutralLanguage>en-US</NeutralLanguage>
        <SatelliteResourceLanguages>en;de</SatelliteResourceLanguages>

        <!-- Code quality -->
        <TreatWarningsAsErrors Condition="'$(CI)' != '' Or '$(TREAT_WARNINGS_AS_ERRORS)' == 'true'">true</TreatWarningsAsErrors>
        <NoWarn Condition="'$(CI)' == ''">$(NoWarn);NU1507</NoWarn>

        <!-- NuGet security -->
        <NuGetAuditMode>all</NuGetAuditMode>
    </PropertyGroup>

    <!-- For repos that contain projects published as NuGet packages -->
    <PropertyGroup>
        <!-- https://docs.microsoft.com/de-de/nuget/reference/msbuild-targets -->
        <PackageProjectUrl>https://gitlab.com/vicione-oss/vicione/suite/suite</PackageProjectUrl>
        <Authors>$(Company)</Authors>
    </PropertyGroup>

    <!-- Performance optimization for CI pipelines -->
    <PropertyGroup Condition="'$(CI)' != ''">
        <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
        <RunAnalyzers>true</RunAnalyzers>
    </PropertyGroup>

    <!-- Do not pack or publish test projects -->
    <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <CompressionEnabled>false</CompressionEnabled>
        <NoWarn>CS1591</NoWarn>
        <!-- Suppress documentation of public API -->
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsPublishable>true</IsPublishable>

        <!-- Use the Microsoft Testing Platform runner (instead of VSTest) to enable the MTP command-line experience -->
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>

        <!-- Emit test results per project to match with 'tests/**/TestResults/*.cobertura.xml' expected in CI -->
        <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --results-directory "$(MSBuildProjectDirectory)/bin/$(Configuration)/$(TargetFramework)/TestResults"</TestingPlatformCommandLineArguments>
        <TestingPlatformConfigurationFilePath>$(MSBuildThisFileDirectory)/tests/testconfig.json</TestingPlatformConfigurationFilePath>
    </PropertyGroup>

    <!-- Configure xunit runner for test projects -->
    <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <Content Include="$(MSBuildThisFileDirectory)/tests/xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <!-- Add Test.SDK/XUnit package references to test projects -->
    <ItemGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="xunit.v3.mtp-v2" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ViciOne.Suite.Sdk.Testing" />

        <!-- Global usings for all test projects -->
        <Using Include="AwesomeAssertions" />
        <Using Include="Xunit" />
        <Using Include="NSubstitute" />
    </ItemGroup>

    <!-- Do not publish tools projects -->
    <PropertyGroup Condition="$(MSBuildProjectDirectory.Contains('tools'))">
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

    <!-- For all client projects -->
    <PropertyGroup Condition="$(ProjectName.EndsWith('.Client'))">
        <!-- https://github.com/koenvzeijl/AspNetCore.SassCompiler/issues/160 -->
        <SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>
    </PropertyGroup>

    <!-- Remove SDK assemblies from backend module output folders -->
    <Target Name="EnsureSdkGetsRemovedIssue" AfterTargets="GenerateDepsFile" Condition="'$(Configuration)' == 'Release' And $(ProjectName.EndsWith('.Backend'))">
        <ItemGroup>
            <FilesToClean Include="$(TargetDir)ViciOne.Suite.Sdk.*" />
        </ItemGroup>
        <Delete Files="@(FilesToClean)"></Delete>
    </Target>
</Project>
