<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <DotNetVersion>10.0.8</DotNetVersion>
    <HostManagementVersion>1.3.0</HostManagementVersion>
    <OpenTelemetryVersion>1.15.0</OpenTelemetryVersion>
    <MassTransitVersion>8.5.9</MassTransitVersion>
    <ViciOneUiBlazorComponentsVersion>5.12.0</ViciOneUiBlazorComponentsVersion>
    <ViciOneUiMonochromeIconsVersion>4.10.0</ViciOneUiMonochromeIconsVersion>
    <ViciOneSuiteSdkVersion>2.0.1</ViciOneSuiteSdkVersion>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="ViciOne.CodeAnalysis" Version="1.6.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.SassCompiler" Version="1.99.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="DevExpress.Blazor" Version="24.2.12" />
    <PackageVersion Include="Fluid.Core" Version="2.31.0" />
    <PackageVersion Include="HostManagement.Shared" Version="$(HostManagementVersion)" />
    <PackageVersion Include="HostManagement.Shared.Communication" Version="$(HostManagementVersion)" />
    <PackageVersion Include="MailKit" Version="4.16.0" />
    <PackageVersion Include="MassTransit" Version="$(MassTransitVersion)" />
    <PackageVersion Include="MassTransit.EntityFrameworkCore" Version="$(MassTransitVersion)" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="$(MassTransitVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.App.Internal.Assets" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyModel" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.TypeScript.MSBuild" Version="5.9.3" />
    <PackageVersion Include="minisign-net" Version="1.0.0" />
    <PackageVersion Include="MQTTnet" Version="5.1.0.1559" />
    <PackageVersion Include="Npgsql" Version="10.0.2" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="$(OpenTelemetryVersion)" />
    <PackageVersion Include="Riok.Mapperly" Version="4.3.1" />
    <PackageVersion Include="Semver" Version="3.0.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Expressions" Version="5.0.0" />
    <PackageVersion Include="Serilog.Sinks.Journal" Version="1.2.0" />
    <PackageVersion Include="StronglyTypedId" Version="0.2.1" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.1" />
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="$(DotNetVersion)" />
    <PackageVersion Include="TimeZoneNames" Version="7.0.0" />
    <PackageVersion Include="ViciOne.Journal" Version="1.2.0" />
    <PackageVersion Include="ViciOne.Suite.Sdk" Version="$(ViciOneSuiteSdkVersion)" />
    <PackageVersion Include="ViciOne.Suite.Sdk.Backend" Version="$(ViciOneSuiteSdkVersion)" />
    <PackageVersion Include="ViciOne.Suite.Sdk.Client" Version="$(ViciOneSuiteSdkVersion)" />
    <PackageVersion Include="ViciOne.Suite.Sdk.Deployment" Version="$(ViciOneSuiteSdkVersion)" />
    <PackageVersion Include="ViciOne.SystemMonitoring" Version="1.0.1" />
    <PackageVersion Include="ViciOne.Ui.Design" Version="2.1.0" />
    <PackageVersion Include="ViciOne.Ui.Blazor.Components" Version="$(ViciOneUiBlazorComponentsVersion)" />
    <PackageVersion Include="ViciOne.Ui.Localization" Version="3.3.0" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Assets" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Components" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.Shared.Dx" Version="0.19.1" />
    <PackageVersion Include="ViciOne.Ui.Shared.Extreme" Version="0.19.1" />
    <!--Used for tests only:-->
    <PackageVersion Include="AutoFixture" Version="4.18.1" />
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="bunit" Version="2.7.2" />
    <PackageVersion Include="Extensions.Logging.NSubstitute" Version="1.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.6.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.7.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.1.1" />
    <PackageVersion Include="ViciOne.Ui.TreeEditor" Version="2.0.1" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="ViciOne.Suite.Sdk.Testing" Version="$(ViciOneSuiteSdkVersion)" />
    <PackageVersion Include="ViciOne.Ui.Blazor.Components.TestingHelpers" Version="$(ViciOneUiBlazorComponentsVersion)" />
    <!--Used for tools only:-->
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="$(DotNetVersion)" />
  </ItemGroup>
</Project>
