<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Core.Shared.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core.Shared\Core.Shared.csproj" />
  </ItemGroup>

</Project>
