//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Instance.ControlPanels.Repositories.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArtifactRepositoryControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArtifactRepositoryControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Instance.ControlPanels.Repositories.Localization.ArtifactRepository" +
                            "ControlPanel", typeof(ArtifactRepositoryControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the update source you are currently editing. If you change one of the editable values you need to confirm or cancel your changes to apply it to the system..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source.
        /// </summary>
        internal static string DescriptionBannerTitleOnAdd {
            get {
                return ResourceManager.GetString("DescriptionBannerTitleOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository endpoint is not a valid URL.
        /// </summary>
        internal static string EndpointInvalidUrl {
            get {
                return ResourceManager.GetString("EndpointInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository endpoint must be a secure HTTPS URL.
        /// </summary>
        internal static string EndpointMustBeHttps {
            get {
                return ResourceManager.GetString("EndpointMustBeHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository endpoint is required.
        /// </summary>
        internal static string EndpointRequired {
            get {
                return ResourceManager.GetString("EndpointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch update source information.
        /// </summary>
        internal static string FetchErrorContent {
            get {
                return ResourceManager.GetString("FetchErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token.
        /// </summary>
        internal static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Endpoint.
        /// </summary>
        internal static string TokenEndpoint {
            get {
                return ResourceManager.GetString("TokenEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token endpoint must be an absolute URI.
        /// </summary>
        internal static string TokenEndpointMustBeAbsoluteUri {
            get {
                return ResourceManager.GetString("TokenEndpointMustBeAbsoluteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token endpoint must be a secure HTTPS URL.
        /// </summary>
        internal static string TokenEndpointMustBeHttps {
            get {
                return ResourceManager.GetString("TokenEndpointMustBeHttps", resourceCulture);
            }
        }
    }
}
