// <auto-generated />
#nullable disable

using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Core.OS.Migrations.ApplicationDbContext.Sqlite
{
    [DbContext(typeof(ApplicationDbContextSqlite))]
    [Migration("20220830135029_Application_AddRegistrationTimestamps")]
    partial class Application_AddRegistrationTimestamps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Core.Shared.Instance.InstanceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstTimeRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledModules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InstanceInfo", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
