// <auto-generated />
using System;
using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.OS.Migrations.ApplicationDbContext.Sqlite
{
    [DbContext(typeof(ApplicationDbContextSqlite))]
    partial class ApplicationDbContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Core.Shared.Instance.Contracts.CrossInstanceConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrossInstanceConfiguration", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.InstanceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstTimeRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormattedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InRecoveryMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalledModules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SdkVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstanceInfo", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.Nonce", b =>
                {
                    b.Property<Guid>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.ToTable("Nonces", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.OnboardingState", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowWizardWhenNotCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId");

                    b.ToTable("OnboardingStates", "app");
                });

            modelBuilder.Entity("Core.Shared.UserManagement.Contracts.ExternalIdProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExternalIdProviders", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
