<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Core.Hosting</AssemblyName>
    <RootNamespace>Core.UiHosting</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ViciOne.Suite.Sdk" />
  </ItemGroup>

</Project>
