//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Instance.ControlPanels.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Instance.ControlPanels.Localization.UpdateControlPanel", typeof(UpdateControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a manual backup of the current system settings..
        /// </summary>
        internal static string BackupDescriptionBannerContent {
            get {
                return ResourceManager.GetString("BackupDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System backup and restore.
        /// </summary>
        internal static string BackupDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("BackupDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is not in the correct format. Please only use *.scf files..
        /// </summary>
        internal static string BackupErrorText {
            get {
                return ResourceManager.GetString("BackupErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        internal static string BackupErrorTitle {
            get {
                return ResourceManager.GetString("BackupErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration file:.
        /// </summary>
        internal static string BackupExportConfigurationFile {
            get {
                return ResourceManager.GetString("BackupExportConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually export a system configuration backup file (.scf) and save it to your computer. Please note that this will only save your configuration, not any other data..
        /// </summary>
        internal static string BackupExportText {
            get {
                return ResourceManager.GetString("BackupExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size is limited to 15MB..
        /// </summary>
        internal static string BackupFileLimitReached {
            get {
                return ResourceManager.GetString("BackupFileLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual backup.
        /// </summary>
        internal static string BackupGroupTitle {
            get {
                return ResourceManager.GetString("BackupGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore configuration file:.
        /// </summary>
        internal static string BackupRestoreConfigurationFile {
            get {
                return ResourceManager.GetString("BackupRestoreConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring backup file in progress. System will be restarted immediately..
        /// </summary>
        internal static string BackupRestoreInProgress {
            get {
                return ResourceManager.GetString("BackupRestoreInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the system configuration from an external backup file (.scf). Please note that this will only restore your configuration, not any other data..
        /// </summary>
        internal static string BackupRestoreText {
            get {
                return ResourceManager.GetString("BackupRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During the update process, the system may require a restart to apply changes, and users are encouraged to back up important data to avoid potential loss. Once the update is complete, it is recommended to verify that all functionalities are operating correctly and perform a system diagnostic if necessary..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase all data.
        /// </summary>
        internal static string EraseAllData {
            get {
                return ResourceManager.GetString("EraseAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching available versions failed. See logs for further details..
        /// </summary>
        internal static string FetchAvailableVersionsError {
            get {
                return ResourceManager.GetString("FetchAvailableVersionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching available versions ....
        /// </summary>
        internal static string FetchingAvailableVersions {
            get {
                return ResourceManager.GetString("FetchingAvailableVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash device.
        /// </summary>
        internal static string FlashDevice {
            get {
                return ResourceManager.GetString("FlashDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand all my data will be deleted forever and unrecoverable..
        /// </summary>
        internal static string ResetConfirmationText {
            get {
                return ResourceManager.GetString("ResetConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be completely removed and the device will be restored to its default settings. Are you sure you want to continue?.
        /// </summary>
        internal static string ResetConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset your system to its original factory default settings. All data saved by users on the drives will be deleted and the entire system will be restored to its default settings..
        /// </summary>
        internal static string ResetDescriptionBannerContent {
            get {
                return ResourceManager.GetString("ResetDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to factory default.
        /// </summary>
        internal static string ResetDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("ResetDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this device:.
        /// </summary>
        internal static string ResetDevice {
            get {
                return ResourceManager.GetString("ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset system.
        /// </summary>
        internal static string ResetGroupTitle {
            get {
                return ResourceManager.GetString("ResetGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing reset. The system will be restarted immediately..
        /// </summary>
        internal static string ResetInProgressMessage {
            get {
                return ResourceManager.GetString("ResetInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process removes all user-installed programs, files and custom configurations, essentially wiping the system clean. It&apos;s important to back up any important data beforehand..
        /// </summary>
        internal static string ResetText {
            get {
                return ResourceManager.GetString("ResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will shut down to start the flash process for the device using the specified file. After a successful flash process, the application is restarted..
        /// </summary>
        internal static string SwuFilenameChangedBannerContent {
            get {
                return ResourceManager.GetString("SwuFilenameChangedBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a .swu file or drag &amp; drop it here..
        /// </summary>
        internal static string SwuFileUploadPlaceholder {
            get {
                return ResourceManager.GetString("SwuFileUploadPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System update.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will shutdown, install the selected version and restart on confirmation..
        /// </summary>
        internal static string VersionChangedBannerContent {
            get {
                return ResourceManager.GetString("VersionChangedBannerContent", resourceCulture);
            }
        }
    }
}
