//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Profile.ControlPanels.Passkeys.Services.Localization {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditPasskeyControlPanelSaveHandler {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditPasskeyControlPanelSaveHandler() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Profile.ControlPanels.Passkeys.Services.Localization.EditPasskeyControlPanelSaveHandler", typeof(EditPasskeyControlPanelSaveHandler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The name is already in use by another passkey.
        /// </summary>
        internal static string PasskeyNameAlreadyInUse {
            get {
                return ResourceManager.GetString("PasskeyNameAlreadyInUse", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The new name is invalid or exceeds the maximum length.
        /// </summary>
        internal static string PasskeyNameInvalid {
            get {
                return ResourceManager.GetString("PasskeyNameInvalid", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Passkey not found.
        /// </summary>
        internal static string PasskeyNotFound {
            get {
                return ResourceManager.GetString("PasskeyNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Renaming the passkey failed.
        /// </summary>
        internal static string PasskeyRenameFailed {
            get {
                return ResourceManager.GetString("PasskeyRenameFailed", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string PasskeyUserNotFound {
            get {
                return ResourceManager.GetString("PasskeyUserNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to No user is logged in.
        /// </summary>
        internal static string UserIsNotSet {
            get {
                return ResourceManager.GetString("UserIsNotSet", resourceCulture);
            }
        }
    }
}
