<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.JiTChat.Client</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" PrivateAssets="all" />
    <PackageReference Include="DevExpress.Blazor" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ViciOne.Suite.Sdk.Client" />
    <PackageReference Include="ViciOne.Ui.Design" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="ViciOne.Ui.Localization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JiTChat.Public\JiTChat.Public.csproj" />
  </ItemGroup>

  <!-- Prevent Microsoft.NET.Sdk.Razor from copying unnecessary file -->
  <ItemGroup>
    <Content Update="sasscompiler.json;tsconfig.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Common.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="ConfigureDesignTargets" BeforeTargets="BeforeDesignTargets">
    <PropertyGroup>
      <ColorsScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/colors</ColorsScssOutputFolder>
      <ScrollbarScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/scrollbar</ScrollbarScssOutputFolder>
    </PropertyGroup>
  </Target>

</Project>
