//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Network.ControlPanels.Ntp.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NtpControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NtpControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Network.ControlPanels.Ntp.Components.Localization.NtpControlPanel", typeof(NtpControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NTP settings ensure that your device always maintains an accurate and consistent system time. Synchronization can be performed either with external time servers or within a local network. You can specify one or more time servers that your device will use for time synchronization, ensuring a precise time base in distributed environments. If no time server is explicitly configured, the device will use the system default servers..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback NTP server.
        /// </summary>
        internal static string FallbackNtpServer {
            get {
                return ResourceManager.GetString("FallbackNtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback NTP servers.
        /// </summary>
        internal static string FallbackNtpServerPlural {
            get {
                return ResourceManager.GetString("FallbackNtpServerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fallback NTP server available..
        /// </summary>
        internal static string NoFallbackNtpServerAvailable {
            get {
                return ResourceManager.GetString("NoFallbackNtpServerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or hostname.
        /// </summary>
        internal static string NtpServerFieldPlaceholder {
            get {
                return ResourceManager.GetString("NtpServerFieldPlaceholder", resourceCulture);
            }
        }
        
        internal static string CopyDefaultServersToServerList {
            get {
                return ResourceManager.GetString("CopyDefaultServersToServerList", resourceCulture);
            }
        }
        
        internal static string AddDefaultServersButtonLabel {
            get {
                return ResourceManager.GetString("AddDefaultServersButtonLabel", resourceCulture);
            }
        }
    }
}
