<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Burger.Client</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <PropertyGroup>
    <!-- https://github.com/koenvzeijl/AspNetCore.SassCompiler/issues/160 -->
    <SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="ViciOne.Ui.Blazor.Components" />
    <PackageReference Include="ViciOne.Suite.Sdk.Client" />
    <PackageReference Include="ViciOne.Ui.Design" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Burger.Internal\Burger.Internal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.Burger.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Common.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="ConfigureDesignTargets" BeforeTargets="BeforeDesignTargets">
    <PropertyGroup>
      <ColorsScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/colors</ColorsScssOutputFolder>
      <ScrollbarScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/scrollbar</ScrollbarScssOutputFolder>
    </PropertyGroup>
  </Target>

</Project>
