//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Mqtt.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MqttViewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MqttViewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Mqtt.Localization.MqttViewer", typeof(MqttViewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Messages.
        /// </summary>
        internal static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker Connection.
        /// </summary>
        internal static string BrokerConnection {
            get {
                return ResourceManager.GetString("BrokerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect to selected Broker.
        /// </summary>
        internal static string ConnectTitle {
            get {
                return ResourceManager.GetString("ConnectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display MQTT messages.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File tree.
        /// </summary>
        internal static string FileTree {
            get {
                return ResourceManager.GetString("FileTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Message.
        /// </summary>
        internal static string FilterByMessage {
            get {
                return ResourceManager.GetString("FilterByMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Topic.
        /// </summary>
        internal static string FilterByTopic {
            get {
                return ResourceManager.GetString("FilterByTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reload interval can not be greater than 5000 ms and less than 200 ms..
        /// </summary>
        internal static string IntervalError {
            get {
                return ResourceManager.GetString("IntervalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Counter.
        /// </summary>
        internal static string MessageCounter {
            get {
                return ResourceManager.GetString("MessageCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Details.
        /// </summary>
        internal static string MessageDetails {
            get {
                return ResourceManager.GetString("MessageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections defined..
        /// </summary>
        internal static string NoConnections {
            get {
                return ResourceManager.GetString("NoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Interval.
        /// </summary>
        internal static string ReloadInterval {
            get {
                return ResourceManager.GetString("ReloadInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Messages.
        /// </summary>
        internal static string SelectedMessages {
            get {
                return ResourceManager.GetString("SelectedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Viewer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Seletion.
        /// </summary>
        internal static string TopicSelection {
            get {
                return ResourceManager.GetString("TopicSelection", resourceCulture);
            }
        }
    }
}
