//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Popup.Factories.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TimedMessagesFactory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimedMessagesFactory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Popup.Factories.Localization.TimedMessagesFactory", typeof(TimedMessagesFactory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is still running. Please wait..
        /// </summary>
        internal static string TimedMessage1 {
            get {
                return ResourceManager.GetString("TimedMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is taking longer than expected. Please keep on waiting a little longer..
        /// </summary>
        internal static string TimedMessage2 {
            get {
                return ResourceManager.GetString("TimedMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is running way to long. Maybe something timed out..
        /// </summary>
        internal static string TimedMessage3 {
            get {
                return ResourceManager.GetString("TimedMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I guess this is not happening anymore. Please reload the page and try again..
        /// </summary>
        internal static string TimedMessage4 {
            get {
                return ResourceManager.GetString("TimedMessage4", resourceCulture);
            }
        }
    }
}
