//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Server.Backend.Areas.Identity.Pages.Account.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blazor.Server.Backend.Areas.Identity.Pages.Account.Localization.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string NoAccountYet {
            get {
                return ResourceManager.GetString("NoAccountYet", resourceCulture);
            }
        }
        
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string WaitingForConnection {
            get {
                return ResourceManager.GetString("WaitingForConnection", resourceCulture);
            }
        }
        
        public static string ExternalLoginFailed {
            get {
                return ResourceManager.GetString("ExternalLoginFailed", resourceCulture);
            }
        }
        
        public static string NoLocalUser {
            get {
                return ResourceManager.GetString("NoLocalUser", resourceCulture);
            }
        }
        
        public static string UnknownExternalUser {
            get {
                return ResourceManager.GetString("UnknownExternalUser", resourceCulture);
            }
        }
        
        public static string LoginUsingExternalProvider {
            get {
                return ResourceManager.GetString("LoginUsingExternalProvider", resourceCulture);
            }
        }
    }
}
