<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.JiTChat.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\JiTChat.Backend\JiTChat.Backend.csproj" />
    <ProjectReference Include="..\..\samples\JiTChat.Client\JiTChat.Client.csproj" />
    <ProjectReference Include="..\Blazor.Tests.Tools\Blazor.Tests.Tools.csproj" />
  </ItemGroup>

</Project>
