<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Blazor.Tests.Tools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Blazor" />
    <PackageReference Include="ViciOne.Ui.Blazor.Components" />
    <PackageReference Include="Bunit" />
    <PackageReference Include="ViciOne.Suite.Sdk.Testing" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
  
</Project>
