<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Blazor.Wasm.Backend</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <RootNamespace>Blazor.Wasm.Backend</RootNamespace>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blazor.Wasm.Client\Blazor.Wasm.Client.csproj" />
    <ProjectReference Include="..\Blazor.DevAssets\Blazor.DevAssets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.Blazor.Wasm.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
  
</Project>
