<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Core.Tests.Tools</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ViciOne.Suite.Sdk.Backend" />
    <PackageReference Include="ViciOne.Suite.Sdk.Testing" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Core.Module\Core.Module.csproj" />
    <ProjectReference Include="..\TestSystem.Backend\TestSystem.Backend.csproj" />
    <ProjectReference Include="..\TestUiHost.Backend\TestUiHost.Backend.csproj" />
    <ProjectReference Include="..\TestModule.Backend\TestModule.Backend.csproj" />
    <ProjectReference Include="..\TestModule.Client\TestModule.Client.csproj" />
  </ItemGroup>

</Project>
