//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Localization.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator or try to open your application in a new browser window..
        /// </summary>
        internal static string AdministratorText {
            get {
                return ResourceManager.GetString("AdministratorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication in progress.
        /// </summary>
        internal static string AuthenticationInProgress {
            get {
                return ResourceManager.GetString("AuthenticationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the server has been interrupted. This can happen, for example, due to a system restart, a network issue or a hardware error..
        /// </summary>
        internal static string InterruptionText {
            get {
                return ResourceManager.GetString("InterruptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of installed modules.
        /// </summary>
        internal static string ModulesViewDescription {
            get {
                return ResourceManager.GetString("ModulesViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        internal static string ModulesViewTitle {
            get {
                return ResourceManager.GetString("ModulesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display mqtt messages.
        /// </summary>
        internal static string MqttViewerDescription {
            get {
                return ResourceManager.GetString("MqttViewerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mqtt Viewer.
        /// </summary>
        internal static string MqttViewerTitle {
            get {
                return ResourceManager.GetString("MqttViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not allowed in here.
        /// </summary>
        internal static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be automatically redirected as soon as the connection is re-established. This can take up to 5 minutes..
        /// </summary>
        internal static string RedirectText {
            get {
                return ResourceManager.GetString("RedirectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection interrupted.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be patient for a moment and do not leave this page..
        /// </summary>
        internal static string WaitText {
            get {
                return ResourceManager.GetString("WaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. A connection to the server could not be established repeatedly..
        /// </summary>
        internal static string WentWrongText {
            get {
                return ResourceManager.GetString("WentWrongText", resourceCulture);
            }
        }
    }
}
