//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Network.ControlPanels.Proxies.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProxiesControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProxiesControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Network.ControlPanels.Proxies.Components.Localization.ProxiesContro" +
                            "lPanel", typeof(ProxiesControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, you can configure proxy settings for your devices. A proxy is an intermediary service that sits between a client, such as a web browser, and the internet, managing the exchange of requests and responses between them. It serves multiple purposes, including enhancing security, preserving anonymity, filtering content, caching data, and optimizing performance..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy settings.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname / IP.
        /// </summary>
        internal static string DoNotProxyListFieldLabel {
            get {
                return ResourceManager.GetString("DoNotProxyListFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. localhost, 172.199.1.9.0.
        /// </summary>
        internal static string DoNotProxyListFieldTextBoxPlaceholder {
            get {
                return ResourceManager.GetString("DoNotProxyListFieldTextBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use proxy settings for the following hosts and domains:.
        /// </summary>
        internal static string DoNotProxyListSettingsGroupTitle {
            get {
                return ResourceManager.GetString("DoNotProxyListSettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP proxy.
        /// </summary>
        internal static string FtpProxySettingsGroupTitle {
            get {
                return ResourceManager.GetString("FtpProxySettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web proxy (HTTP).
        /// </summary>
        internal static string HttpProxySettingsGroupTitle {
            get {
                return ResourceManager.GetString("HttpProxySettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure web proxy (HTTPS).
        /// </summary>
        internal static string HttpsProxySettingsGroupTitle {
            get {
                return ResourceManager.GetString("HttpsProxySettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure FTP proxy.
        /// </summary>
        internal static string SftpProxySettingsGroupTitle {
            get {
                return ResourceManager.GetString("SftpProxySettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks proxy.
        /// </summary>
        internal static string SocksProxySettingsGroupTitle {
            get {
                return ResourceManager.GetString("SocksProxySettingsGroupTitle", resourceCulture);
            }
        }
    }
}
