//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Profile.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExternalIdProviders {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExternalIdProviders() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blazor.Shared.Profile.Localization.ExternalIdProviders", typeof(ExternalIdProviders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string NoProviderConfigured {
            get {
                return ResourceManager.GetString("NoProviderConfigured", resourceCulture);
            }
        }
        
        public static string NoLinkedAccount {
            get {
                return ResourceManager.GetString("NoLinkedAccount", resourceCulture);
            }
        }
        
        public static string LinkedAccount {
            get {
                return ResourceManager.GetString("LinkedAccount", resourceCulture);
            }
        }

        public static string UnlinkAccount {
            get {
                return ResourceManager.GetString("UnlinkAccount", resourceCulture);
            }
        }

        public static string UnlinkConfirmationBody {
            get {
                return ResourceManager.GetString("UnlinkConfirmationBody", resourceCulture);
            }
        }

        public static string UnlinkFailedLastCredential {
            get {
                return ResourceManager.GetString("UnlinkFailedLastCredential", resourceCulture);
            }
        }

        public static string UnlinkFailed {
            get {
                return ResourceManager.GetString("UnlinkFailed", resourceCulture);
            }
        }
    }
}
