//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Profile.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blazor.Shared.Profile.Localization.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorSavingPasskey {
            get {
                return ResourceManager.GetString("ErrorSavingPasskey", resourceCulture);
            }
        }
        
        internal static string UserIsNotSet {
            get {
                return ResourceManager.GetString("UserIsNotSet", resourceCulture);
            }
        }
        
        internal static string UnknownErrorDuringDeletion {
            get {
                return ResourceManager.GetString("UnknownErrorDuringDeletion", resourceCulture);
            }
        }

        internal static string PasskeyUserNotFound {
            get {
                return ResourceManager.GetString("PasskeyUserNotFound", resourceCulture);
            }
        }

        internal static string PasskeyNotFound {
            get {
                return ResourceManager.GetString("PasskeyNotFound", resourceCulture);
            }
        }

        internal static string PasskeyNameInvalid {
            get {
                return ResourceManager.GetString("PasskeyNameInvalid", resourceCulture);
            }
        }

        internal static string PasskeyNameAlreadyInUse {
            get {
                return ResourceManager.GetString("PasskeyNameAlreadyInUse", resourceCulture);
            }
        }

        internal static string PasskeyRenameFailed {
            get {
                return ResourceManager.GetString("PasskeyRenameFailed", resourceCulture);
            }
        }
    }
}
