<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AssemblyName>ViciOne.Suite.Blazor.Server.Backend</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <RootNamespace>Blazor.Server.Backend</RootNamespace>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <PropertyGroup>
    <!-- https://github.com/koenvzeijl/AspNetCore.SassCompiler/issues/160 -->
    <SassCompilerEnableWatcher>false</SassCompilerEnableWatcher>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blazor.DevAssets\Blazor.DevAssets.csproj" />
    <ProjectReference Include="..\Blazor.Shared\Blazor.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="AspNetCore.SassCompiler" PrivateAssets="all" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="ViciOne.Ui.Design" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <!-- Prevent Microsoft.NET.Sdk.Razor from copying unnecessary file -->
  <ItemGroup>
    <Content Update="sasscompiler.json;" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" Pack="False" />
    <Content Update="package*.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" Pack="False" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Pages/*.razor.css" CssScope="suite-server" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ViciOne.Suite.Blazor.Server.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Areas\Identity\Pages\Account\Localization\ChangePassword.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ChangePassword.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\ConfirmEmail.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConfirmEmail.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\ForgotPasswordConfirmation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ForgotPasswordConfirmation.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\Login.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Login.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\EmailConfirmation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailConfirmation.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\ChangePassword.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ChangePassword.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\ResendEmailConfirmation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResendEmailConfirmation.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\ResetPassword.Designer.cs">
      <DependentUpon>ResetPassword.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Account\Localization\ResetPasswordConfirmation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResetPasswordConfirmation.resx</DependentUpon>
    </Compile>
    <Compile Update="Areas\Identity\Pages\Models\Localization\ModelValidation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ModelValidation.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\BlazorServerClientModule.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Validation.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\ChangePassword.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ChangePassword.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\Common.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\ConfirmEmail.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ConfirmEmail.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\ForgotPasswordConfirmation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ForgotPasswordConfirmation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\Login.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Login.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\EmailConfirmation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>EmailConfirmation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\ChangePassword.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ChangePassword.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Common.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\ResendEmailConfirmation.de.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\ResendEmailConfirmation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResendEmailConfirmation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\ResetPassword.resx">
      <LastGenOutput>ResetPassword.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Account\Localization\ResetPasswordConfirmation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResetPasswordConfirmation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Areas\Identity\Pages\Models\Localization\ModelValidation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ModelValidation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\Login.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="DeleteDevExpressWwwrootContent" AfterTargets="Publish">
    <ItemGroup>
      <!-- it's worth removing it to save ~17MB -->
      <FilesToDelete Include="$(PublishDir)\wwwroot\_content\DevExpress.Blazor.Resources\js\devextreme\dx.all.debug.js" />
      <FilesToDelete Include="$(PublishDir)\wwwroot\_content\DevExpress.Blazor.Resources\js\analytics-core\dx-analytics-core.js" />
      <FilesToDelete Include="$(PublishDir)\wwwroot\_content\DevExpress.Blazor.Resources\js\analytics-core\dx-querybuilder.js" />
    </ItemGroup>

    <RemoveDir Directories="$(PublishDir)\wwwroot\_content\DevExpress.Blazor.Themes" />

    <Delete Files="@(FilesToDelete)">
      <Output TaskParameter="DeletedFiles" ItemName="DeletedList" />
    </Delete>

    <Message Text="Deleted DexExpress themes and '@(DeletedList)'" Importance="high" />
  </Target>

  <Target Name="DeleteWwwrootIdentityContent" AfterTargets="Publish">
    <RemoveDir Directories="$(PublishDir)\wwwroot\Identity" />
    <Message Text="Deleted identity web content" Importance="high" />
  </Target>

  <Target Name="ConfigureDesignTargets" BeforeTargets="BeforeDesignTargets">
    <PropertyGroup>
      <ColorsScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/colors</ColorsScssOutputFolder>
      <ScrollbarScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/scrollbar</ScrollbarScssOutputFolder>
    </PropertyGroup>
  </Target>

  <PropertyGroup>
    <_BlazorWebJs>_framework\blazor.web.js</_BlazorWebJs>
    <_BlazorWebJsStaticWebAssetFile>wwwroot\$(_BlazorWebJs)</_BlazorWebJsStaticWebAssetFile>
    <_BlazorWebJsSource>$(NuGetPackageRoot)\microsoft.aspnetcore.app.internal.assets\$(DotNetVersion)\$(_BlazorWebJs)</_BlazorWebJsSource>
    <_BlazorWebJsDest>$(MSBuildProjectDirectory)\$(_BlazorWebJsStaticWebAssetFile)</_BlazorWebJsDest>
  </PropertyGroup>

  <!--
    This target was introduced with .NET 10 update where UseStaticFiles does not include the blazor.web.js anymore.

    See https://github.com/Lapiniot/Net.MQTT/issues/116 and https://github.com/dotnet/aspnetcore/issues/64381#issuecomment-3546832403.
  -->
  <Target Name="CopyBlazorWebJsToWwwrootFramework" BeforeTargets="PreBuildEvent">
    <Error Condition="!Exists('$(_BlazorWebJsSource)')" Text="'$(_BlazorWebJsSource)' not found. Ensure Microsoft.AspNetCore.App.Internal.Assets is restored and version is set correctly." />

    <Message Text="Copying '$(_BlazorWebJsSource)' to '$(_BlazorWebJsDest)'" Importance="high" />
   
    <MakeDir Directories="$([System.IO.Path]::GetDirectoryName($(_BlazorWebJsDest)))" />
    <Copy SourceFiles="$(_BlazorWebJsSource)" DestinationFiles="$(_BlazorWebJsDest)"/>

    <ItemGroup>
      <!--
        @(Content) is passed to DiscoverStaticWebAssets task in an early stage of the build, way before our copy steps will execute.
        This results in the build system / targets / tasks not knowing about the file copied.
        We fix this by adding a content item for the file copied.
      -->
      <Content Include="$(_BlazorWebJsStaticWebAssetFile)" Condition="!@(Content->AnyHaveMetadataValue('Identity', $(_BlazorWebJsStaticWebAssetFile)))" />
    </ItemGroup>
  </Target>

  <Target Name="CleanBlazorWebJs" BeforeTargets="Clean" Condition="Exists('$(_BlazorWebJsDest)')">
    <Delete Files="$(_BlazorWebJsDest)" />

    <ItemGroup>
      <Content Remove="$(_BlazorWebJsDest)" Condition="@(Content-&gt;AnyHaveMetadataValue('Identity', $(_BlazorWebJsDest)))" />
    </ItemGroup>
  </Target>

</Project>
