// <auto-generated />
using System;
using Burger.Backend.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Burger.Backend.Ef.Migrations.BurgerDbContext.Sqlite
{
    [DbContext(typeof(BurgerDbContextSqlite))]
    [Migration("20220725135547_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("burger")
                .HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Burger.Backend.StateMachines.OrderBurgerState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Burgers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentState")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("CorrelationId");

                    b.ToTable("OrderBurgerState", "burger");
                });
#pragma warning restore 612, 618
        }
    }
}
