//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.UserManagement.ControlPanels.User.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.UserManagement.ControlPanels.User.Components.Localization.UserContr" +
                            "olPanel", typeof(UserControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perm..
        /// </summary>
        internal static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active 2-Factor-Authentification.
        /// </summary>
        internal static string ActiveTwoFactorAuthentification {
            get {
                return ResourceManager.GetString("ActiveTwoFactorAuthentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor sit amet.
        /// </summary>
        internal static string AppsDescriptionBannerContent {
            get {
                return ResourceManager.GetString("AppsDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit permissions for user.
        /// </summary>
        internal static string AppsDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("AppsDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the fields and hit confirm to add the user..
        /// </summary>
        internal static string DescriptionBannerContentOnAdd {
            get {
                return ResourceManager.GetString("DescriptionBannerContentOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, you can edit the data of the user. Change the current input and hit confirm to apply your changes to the user..
        /// </summary>
        internal static string DescriptionBannerContentOnEdit {
            get {
                return ResourceManager.GetString("DescriptionBannerContentOnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        internal static string DescriptionBannerTitleOnAdd {
            get {
                return ResourceManager.GetString("DescriptionBannerTitleOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        internal static string DescriptionBannerTitleOnEdit {
            get {
                return ResourceManager.GetString("DescriptionBannerTitleOnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor sit amet.
        /// </summary>
        internal static string DevicesDescriptionBannerContent {
            get {
                return ResourceManager.GetString("DevicesDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign devices to user.
        /// </summary>
        internal static string DevicesDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DevicesDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password expiration date.
        /// </summary>
        internal static string PasswordExpirationDate {
            get {
                return ResourceManager.GetString("PasswordExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant user specific permissions and access levels. This should only be necessary in rare cases. To manage the user&apos;s overall permissions, see the &quot;Roles&quot; tab..
        /// </summary>
        internal static string PermissionsDescriptionBannerContent {
            get {
                return ResourceManager.GetString("PermissionsDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user permissions: {0}.
        /// </summary>
        internal static string PermissionsDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("PermissionsDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports to.
        /// </summary>
        internal static string ReportsTo {
            get {
                return ResourceManager.GetString("ReportsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the user&apos;s roles..
        /// </summary>
        internal static string RolesDescriptionBannerContent {
            get {
                return ResourceManager.GetString("RolesDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user roles.
        /// </summary>
        internal static string RolesDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("RolesDescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor sit amet.
        /// </summary>
        internal static string TimeDescriptionBannerContent {
            get {
                return ResourceManager.GetString("TimeDescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time settings.
        /// </summary>
        internal static string TimeDescriptionBannerTitle {
            get {
                return ResourceManager.GetString("TimeDescriptionBannerTitle", resourceCulture);
            }
        }
    }
}
