//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Module.ControlPanels.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModuleManagementControlPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleManagementControlPanel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Module.ControlPanels.Localization.ModuleManagementControlPanel", typeof(ModuleManagementControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Modules.
        /// </summary>
        internal static string BrowseModules {
            get {
                return ResourceManager.GetString("BrowseModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the store for available modules. Note that changes will take effect only after restarting the application..
        /// </summary>
        internal static string BrowseModulesBanner {
            get {
                return ResourceManager.GetString("BrowseModulesBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand to see options provided by the module.
        /// </summary>
        internal static string ExpandToSeeOptionsProvidedByTheModule {
            get {
                return ResourceManager.GetString("ExpandToSeeOptionsProvidedByTheModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Modules.
        /// </summary>
        internal static string InstalledModules {
            get {
                return ResourceManager.GetString("InstalledModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViciOne is a modular system that can be expanded by installing additional modules. Here, you can manage the installed modules of the suite. You can install, uninstall, and update modules individually. If needed, access to pre-releases is also available. Please note: Changes to the modules take effect only after a system restart..
        /// </summary>
        internal static string InstalledModulesBanner {
            get {
                return ResourceManager.GetString("InstalledModulesBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module API Error.
        /// </summary>
        internal static string ModuleApiError {
            get {
                return ResourceManager.GetString("ModuleApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modules available for installation.
        /// </summary>
        internal static string NoModulesAvailableToInstall {
            get {
                return ResourceManager.GetString("NoModulesAvailableToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modules installed, yet.
        /// </summary>
        internal static string NoModulesInstalledYet {
            get {
                return ResourceManager.GetString("NoModulesInstalledYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options provided or defined yet..
        /// </summary>
        internal static string NoOptionsProvidedOrDefinedYet {
            get {
                return ResourceManager.GetString("NoOptionsProvidedOrDefinedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use an action from the toolbar.
        /// </summary>
        internal static string PleaseUseToolBarAction {
            get {
                return ResourceManager.GetString("PleaseUseToolBarAction", resourceCulture);
            }
        }
    }
}
