//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Onboarding.Components.WizardPages.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HostnameWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HostnameWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Onboarding.Components.WizardPages.Localization.HostnameWizardPage", typeof(HostnameWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname is the unique name that identifies your device on a network. It is used to distinguish this device from others and is essential for network communication..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hostname.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hostname.
        /// </summary>
        internal static string EnterHostnameTitle {
            get {
                return ResourceManager.GetString("EnterHostnameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hostname can be changed later in settings if needed..
        /// </summary>
        internal static string Rule1 {
            get {
                return ResourceManager.GetString("Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hostname must adhere to the following rules:.
        /// </summary>
        internal static string Rule2 {
            get {
                return ResourceManager.GetString("Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length: between 1 and {0} characters.
        /// </summary>
        internal static string Rule2a {
            get {
                return ResourceManager.GetString("Rule2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters allowed: only alphanumeric characters (A-Z, a-z, 0-9) and hyphens (-).
        /// </summary>
        internal static string Rule2b {
            get {
                return ResourceManager.GetString("Rule2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start / end: must not start or end with a hyphen.
        /// </summary>
        internal static string Rule2c {
            get {
                return ResourceManager.GetString("Rule2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitivity: Hostnames are case-insensitive.
        /// </summary>
        internal static string Rule2d {
            get {
                return ResourceManager.GetString("Rule2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules &amp; guidelines for selecting a hostname.
        /// </summary>
        internal static string RulesAndGuidelinesTitle {
            get {
                return ResourceManager.GetString("RulesAndGuidelinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step ensures your device is correctly identified within the network environment..
        /// </summary>
        internal static string StepPurposeNotice {
            get {
                return ResourceManager.GetString("StepPurposeNotice", resourceCulture);
            }
        }
    }
}
