//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Onboarding.Components.WizardPages.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetworkWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Onboarding.Components.WizardPages.Localization.NetworkWizardPage", typeof(NetworkWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IP address of the router for external communication..
        /// </summary>
        internal static string DefaultGatewayExplanation {
            get {
                return ResourceManager.GetString("DefaultGatewayExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This step configures the device&apos;s network settings, including IP addresses, subnet masks, default gateways, DNS servers.
        ///Correct network configuration ensures the device can communicate effectively within local networks and access the internet..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network setup.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network settings can be adjusted later via the settings menu..
        /// </summary>
        internal static string IntermediateSentence {
            get {
                return ResourceManager.GetString("IntermediateSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique identifier for the device on the network..
        /// </summary>
        internal static string IpAddressExplanation {
            get {
                return ResourceManager.GetString("IpAddressExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN configuration.
        /// </summary>
        internal static string Rule1 {
            get {
                return ResourceManager.GetString("Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Recommended for the local network (e.g., internal communications).
        /// </summary>
        internal static string Rule1a {
            get {
                return ResourceManager.GetString("Rule1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Typically used for internet connectivity.
        /// </summary>
        internal static string Rule1b {
            get {
                return ResourceManager.GetString("Rule1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address assignment configuration options.
        /// </summary>
        internal static string Rule2 {
            get {
                return ResourceManager.GetString("Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (DHCP): The recommended and most common method, where the network settings are assigned automatically by the network..
        /// </summary>
        internal static string Rule2a {
            get {
                return ResourceManager.GetString("Rule2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual: Allows you to specify IP addresses, subnet masks, and the default gateway manually. This option may require input from your network administrator..
        /// </summary>
        internal static string Rule2b {
            get {
                return ResourceManager.GetString("Rule2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important note.
        /// </summary>
        internal static string Rule3 {
            get {
                return ResourceManager.GetString("Rule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one default gateway is allowed to avoid routing conflicts and ensure proper network communication..
        /// </summary>
        internal static string Rule3a {
            get {
                return ResourceManager.GetString("Rule3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple DNS server addresses can be added for redundancy..
        /// </summary>
        internal static string Rule3b {
            get {
                return ResourceManager.GetString("Rule3b", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DNS configuration.
        /// </summary>
        internal static string Rule4 {
            get {
                return ResourceManager.GetString("Rule4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DNS (Domain Name System) translates domain names into IP addresses, allowing the device to resolve network addresses..
        /// </summary>
        internal static string Rule4a {
            get {
                return ResourceManager.GetString("Rule4a", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When enabled, specify at least one DNS server address. If no DNS server is configured, name resolution may not function..
        /// </summary>
        internal static string Rule4b {
            get {
                return ResourceManager.GetString("Rule4b", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rules &amp; guidelines for configuring your network.
        /// </summary>
        internal static string RulesAndGuidelinesTitle {
            get {
                return ResourceManager.GetString("RulesAndGuidelinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server that resolves human-readable domain names (e.g., www.example.com) into IP addresses..
        /// </summary>
        internal static string DnsServerExplanation {
            get {
                return ResourceManager.GetString("DnsServerExplanation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A 32 bit address used to divide an IP address into network portion and host portion..
        /// </summary>
        internal static string SubnetMaskExplanation {
            get {
                return ResourceManager.GetString("SubnetMaskExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms explained.
        /// </summary>
        internal static string TermsExplained {
            get {
                return ResourceManager.GetString("TermsExplained", resourceCulture);
            }
        }
    }
}
