//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Onboarding.Components.WizardPages.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Onboarding.Components.WizardPages.Localization.PasswordWizardPage", typeof(PasswordWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Administrator is a privileged user responsible for managing the device, configuring key settings, and ensuring the system operates securely. As the Administrator, you should choose a strong and secure password to protect your device from unauthorized access..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the administrator password.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter administrator data.
        /// </summary>
        internal static string EnterAdministratorDataTitle {
            get {
                return ResourceManager.GetString("EnterAdministratorDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using personal information, such as names, brithdays or common words..
        /// </summary>
        internal static string Guideline1 {
            get {
                return ResourceManager.GetString("Guideline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administrator password can be changed at any time via the settings menu if needed..
        /// </summary>
        internal static string IntermediateSentence {
            get {
                return ResourceManager.GetString("IntermediateSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters long.
        /// </summary>
        internal static string Rule1 {
            get {
                return ResourceManager.GetString("Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a combination of the following characters:.
        /// </summary>
        internal static string Rule2 {
            get {
                return ResourceManager.GetString("Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase letters (A-Z).
        /// </summary>
        internal static string Rule2a {
            get {
                return ResourceManager.GetString("Rule2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase letter (a-z).
        /// </summary>
        internal static string Rule2b {
            get {
                return ResourceManager.GetString("Rule2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers (0-9).
        /// </summary>
        internal static string Rule2c {
            get {
                return ResourceManager.GetString("Rule2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters (e.g. !, @, #, $, %, ^, &amp;, *).
        /// </summary>
        internal static string Rule2d {
            get {
                return ResourceManager.GetString("Rule2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules &amp; guidelines for selecting a password.
        /// </summary>
        internal static string RulesAndGuidelinesTitle {
            get {
                return ResourceManager.GetString("RulesAndGuidelinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat your administrator password as sensitive information. Store it securely and avoid sharing it with others unless absolutely necessary..
        /// </summary>
        internal static string SecurityNotice {
            get {
                return ResourceManager.GetString("SecurityNotice", resourceCulture);
            }
        }
    }
}
