//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Onboarding.Components.WizardPages.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WelcomeWizardPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WelcomeWizardPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Onboarding.Components.WizardPages.Localization.WelcomeWizardPage", typeof(WelcomeWizardPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0}! This wizard will guide you step by step through configuring your device for optimal use. If you prefer a quick setup with the most essential settings, this wizard provides a simple and efficient process. If you prefer manual configuration, you may exit the wizard now..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up administrative security with a strong password..
        /// </summary>
        internal static string InitialTask1 {
            get {
                return ResourceManager.GetString("InitialTask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure essential device settings, including network and time zone..
        /// </summary>
        internal static string InitialTask2 {
            get {
                return ResourceManager.GetString("InitialTask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial tasks.
        /// </summary>
        internal static string InitialTaskCaption {
            get {
                return ResourceManager.GetString("InitialTaskCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can adjust any settings made during this wizard later via the settings menu..
        /// </summary>
        internal static string IntermediateSentence {
            get {
                return ResourceManager.GetString("IntermediateSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is handled according to strict privacy standards..
        /// </summary>
        internal static string PrivacyNote1 {
            get {
                return ResourceManager.GetString("PrivacyNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network configuration and administrative credentials remain secure and confidential..
        /// </summary>
        internal static string PrivacyNote2 {
            get {
                return ResourceManager.GetString("PrivacyNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For further information, refer to our privacy policy..
        /// </summary>
        internal static string PrivacyNote3 {
            get {
                return ResourceManager.GetString("PrivacyNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy notes.
        /// </summary>
        internal static string PrivacyNotesCaption {
            get {
                return ResourceManager.GetString("PrivacyNotesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What this wizard helps you do.
        /// </summary>
        internal static string SettingsGroupTitle {
            get {
                return ResourceManager.GetString("SettingsGroupTitle", resourceCulture);
            }
        }
    }
}
