//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Network.ControlPanels.NetworkInterface.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralControlPanelPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralControlPanelPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Network.ControlPanels.NetworkInterface.Components.Localization.Gene" +
                            "ralControlPanelPage", typeof(GeneralControlPanelPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display and manage basic information, settings and diagnostic functions of the selected network interface..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General {0} settings.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current network settings are displayed here. This information includes important connection and network details. No changes can be made in this area..
        /// </summary>
        internal static string GeneralInformationDescription {
            get {
                return ResourceManager.GetString("GeneralInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface enabled.
        /// </summary>
        internal static string InterfaceEnabledSettingsGroupTitle {
            get {
                return ResourceManager.GetString("InterfaceEnabledSettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface name.
        /// </summary>
        internal static string InterfaceName {
            get {
                return ResourceManager.GetString("InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string InterfaceNameSettingsGroupTitle {
            get {
                return ResourceManager.GetString("InterfaceNameSettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 address.
        /// </summary>
        internal static string Ipv4Address {
            get {
                return ResourceManager.GetString("Ipv4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 configuration.
        /// </summary>
        internal static string Ipv4Configuration {
            get {
                return ResourceManager.GetString("Ipv4Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Default gateway.
        /// </summary>
        internal static string Ipv4DefaultGateway {
            get {
                return ResourceManager.GetString("Ipv4DefaultGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Subnet mask.
        /// </summary>
        internal static string Ipv4SubnetMask {
            get {
                return ResourceManager.GetString("Ipv4SubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default gateway available.
        /// </summary>
        internal static string IsDefaultGatewayAvailable {
            get {
                return ResourceManager.GetString("IsDefaultGatewayAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default route configured.
        /// </summary>
        internal static string IsDefaultRouteConfigured {
            get {
                return ResourceManager.GetString("IsDefaultRouteConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS functional.
        /// </summary>
        internal static string IsDnsFunctional {
            get {
                return ResourceManager.GetString("IsDnsFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet available.
        /// </summary>
        internal static string IsInternetAvailable {
            get {
                return ResourceManager.GetString("IsInternetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Segmentation.
        /// </summary>
        internal static string NetworkSegmentation {
            get {
                return ResourceManager.GetString("NetworkSegmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this interface to factory default.
        /// </summary>
        internal static string ResetThisInterfaceToFactoryDefault {
            get {
                return ResourceManager.GetString("ResetThisInterfaceToFactoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        internal static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard: 1 - 1005, Extended: 1006 - 4094.
        /// </summary>
        internal static string VLanIdSettingsFieldSubline {
            get {
                return ResourceManager.GetString("VLanIdSettingsFieldSubline", resourceCulture);
            }
        }
    }
}
