//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.Network.ControlPanels.NetworkInterface.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TcpIpControlPanelPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TcpIpControlPanelPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Shared.Network.ControlPanels.NetworkInterface.Components.Localization.TcpI" +
                            "pControlPanelPage", typeof(TcpIpControlPanelPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure all TCP/IP settings such as DHCP, IP address(es), network mask(s) and default gateway of the network interface..
        /// </summary>
        internal static string DescriptionBannerContent {
            get {
                return ResourceManager.GetString("DescriptionBannerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP settings for {0}.
        /// </summary>
        internal static string DescriptionBannerTitle {
            get {
                return ResourceManager.GetString("DescriptionBannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message: &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorBody {
            get {
                return ResourceManager.GetString("ErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 configuration.
        /// </summary>
        internal static string IPv4ConfigurationSettingsGroupTitle {
            get {
                return ResourceManager.GetString("IPv4ConfigurationSettingsGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last fetch.
        /// </summary>
        internal static string LastFetch {
            get {
                return ResourceManager.GetString("LastFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease duration.
        /// </summary>
        internal static string LeaseDuration {
            get {
                return ResourceManager.GetString("LeaseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease end.
        /// </summary>
        internal static string LeaseEnd {
            get {
                return ResourceManager.GetString("LeaseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease start.
        /// </summary>
        internal static string LeaseStart {
            get {
                return ResourceManager.GetString("LeaseStart", resourceCulture);
            }
        }
    }
}
