// <auto-generated />
using System;
using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.OS.Migrations.ConnectionDbContext.Sqlite
{
    [DbContext(typeof(ConnectionDbContextSqlite))]
    [Migration("20230901090414_Connection_Initial")]
    partial class Connection_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("connection")
                .HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Sdk.Connections.Contracts.Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Connections", "connection");
                });

            modelBuilder.Entity("Sdk.Connections.Contracts.ConnectionTag", b =>
                {
                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ConnectionTag", "connection");
                });

            modelBuilder.Entity("Sdk.Connections.Contracts.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Protected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags", "connection");
                });

            modelBuilder.Entity("Sdk.Connections.Contracts.ConnectionTag", b =>
                {
                    b.HasOne("Sdk.Connections.Contracts.Connection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sdk.Connections.Contracts.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
