//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.EnvironmentOverrides.ControlPanels.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvironmentOverridesControlPanel {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvironmentOverridesControlPanel() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blazor.Shared.EnvironmentOverrides.ControlPanels.Localization.EnvironmentOverride" +
                            "sControlPanel", typeof(EnvironmentOverridesControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        internal static string RiskBannerContent {
            get {
                return ResourceManager.GetString("RiskBannerContent", resourceCulture);
            }
        }
        
        internal static string DuplicateKeyError {
            get {
                return ResourceManager.GetString("DuplicateKeyError", resourceCulture);
            }
        }
        
        internal static string InvalidKeyError {
            get {
                return ResourceManager.GetString("InvalidKeyError", resourceCulture);
            }
        }
        
        internal static string InvalidValueError {
            get {
                return ResourceManager.GetString("InvalidValueError", resourceCulture);
            }
        }
        
        internal static string ValueWithoutKeyError {
            get {
                return ResourceManager.GetString("ValueWithoutKeyError", resourceCulture);
            }
        }
        
        internal static string LoadFailedTitle {
            get {
                return ResourceManager.GetString("LoadFailedTitle", resourceCulture);
            }
        }
        
        internal static string SaveBlockedByLoadFailureError {
            get {
                return ResourceManager.GetString("SaveBlockedByLoadFailureError", resourceCulture);
            }
        }
    }
}
