//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Shared.UserManagement.ControlPanels.OpenIdProvider.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenIdProviderControlPanel {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenIdProviderControlPanel() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Blazor.Shared.UserManagement.ControlPanels.OpenIdProvider.Localization.OpenIdPro" +
                            "viderControlPanel", typeof(OpenIdProviderControlPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        internal static string RiskBannerContent {
            get {
                return ResourceManager.GetString("RiskBannerContent", resourceCulture);
            }
        }
        
        internal static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        internal static string AuthorityHint {
            get {
                return ResourceManager.GetString("AuthorityHint", resourceCulture);
            }
        }
        
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        internal static string ClientSecretStoredHint {
            get {
                return ResourceManager.GetString("ClientSecretStoredHint", resourceCulture);
            }
        }
        
        internal static string ClientSecretNotStoredHint {
            get {
                return ResourceManager.GetString("ClientSecretNotStoredHint", resourceCulture);
            }
        }
        
        internal static string ClientSecretRemovalPendingHint {
            get {
                return ResourceManager.GetString("ClientSecretRemovalPendingHint", resourceCulture);
            }
        }
        
        internal static string RemoveStoredClientSecret {
            get {
                return ResourceManager.GetString("RemoveStoredClientSecret", resourceCulture);
            }
        }
        
        internal static string InvalidAuthorityError {
            get {
                return ResourceManager.GetString("InvalidAuthorityError", resourceCulture);
            }
        }
        
        internal static string IncompleteProviderError {
            get {
                return ResourceManager.GetString("IncompleteProviderError", resourceCulture);
            }
        }
        
        internal static string LoadFailedTitle {
            get {
                return ResourceManager.GetString("LoadFailedTitle", resourceCulture);
            }
        }
        
        internal static string SaveBlockedByLoadFailureError {
            get {
                return ResourceManager.GetString("SaveBlockedByLoadFailureError", resourceCulture);
            }
        }
    }
}
