// <auto-generated />
#nullable disable

using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Core.OS.Migrations.ApplicationDbContext.Postgres
{
    [DbContext(typeof(ApplicationDbContextPostgres))]
    [Migration("20240903120646_ApplicationAddSerialNumber")]
    partial class ApplicationAddSerialNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Shared.Instance.InstanceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstTimeRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstalledModules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InstanceInfo", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
