// <auto-generated />
using System;
using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.OS.Migrations.ApplicationDbContext.Postgres
{
    [DbContext(typeof(ApplicationDbContextPostgres))]
    [Migration("20250211204412_ApplicationAddInstanceInformationRecoveryFlag")]
    partial class ApplicationAddInstanceInformationRecoveryFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Shared.Instance.Contracts.InstanceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstTimeRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InRecoveryMode")
                        .HasColumnType("boolean");

                    b.Property<string>("InstalledModules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SdkVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InstanceInfo", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
