// <auto-generated />
using System;
using Core.OS.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.OS.Migrations.ApplicationDbContext.Postgres
{
    [DbContext(typeof(ApplicationDbContextPostgres))]
    [Migration("20260202171219_AddSystemType")]
    partial class AddSystemType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Shared.Instance.Contracts.CrossInstanceConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CrossInstanceConfiguration", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.InstanceInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FirstTimeRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InRecoveryMode")
                        .HasColumnType("boolean");

                    b.Property<string>("InstalledModules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SdkVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InstanceInfo", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.Nonce", b =>
                {
                    b.Property<Guid>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Value");

                    b.ToTable("Nonces", "app");
                });

            modelBuilder.Entity("Core.Shared.Instance.Contracts.OnboardingState", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowWizardWhenNotCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("InstanceId");

                    b.ToTable("OnboardingStates", "app");
                });
#pragma warning restore 612, 618
        }
    }
}
